title: Noise lab
email: gurpritsbagga@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The art of noises should not limit itself to an imitative reproduction -- Luigi Russolo
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sinbag.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sinbagga
github_username:  sinbag

# Build settings
theme: minima
# plugins:
#   - jekyll-seo-tag


defaults:
 -
  scope:
    path: "posts" # empty string means all files
  values:
    layout: "post"
    author: "Gurpreet Singh"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
