title: Garage
email: gsingh@mpi-inf.mpg.de
description: >- # this means to ignore newlines until "baseurl:"
  Mathematical tools with code snippets
theme: minima
baseurl: ""  # This should be empty for local development
url: "http://localhost:4000"
