title: The Ministry of Noise
email: gurpritsbagga@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Research and publications by Gurprit Singh on Monte Carlo sampling, physically based rendering, optimization, and generative AI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sinbag.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
timezone: Europe/Berlin
author:
  name: Gurprit Singh
  url: https://sinbag.github.io/
github_username:  sinbag
header_pages:
  - about.markdown
  - index.markdown

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag


defaults:
 -
  scope:
    path: ""
    type: posts
  values:
    layout: "post"
    author: "Gurprit Singh"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - about1.markdown
  - about2.markdown
  - about_professional.markdown
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
